http:   
  routers:

    proom:     
      rule: "Host(`myDomian`)"
      tls:
        certResolver: myresolver      
      service: 'proom'  

    mqtt:     
      rule: "Host(`myDomian`) && Path(`/mqtt`)"
      tls:
        certResolver: myresolver2           
      service: 'mqtt'

    libre:     
      rule: "Host(`myDomian`) && (PathPrefix(`/lool/`) || PathPrefix(`/loleaflet/`) || PathPrefix(`/hosting/`))"
      tls:
        certResolver: myresolver      
      service: 'libre'

     
    sfu:     
      rule: "Host(`myDomian`) && Path(`/ws`)"
      tls:
        certResolver: myresolver           
      service: 'sfu'


  services:
    proom:
      loadBalancer:        
        servers:         
          - url: http://proom:5000

    mqtt:
      loadBalancer:        
        servers:          
          - url: http://mqtt:9001          
            
    libre:
      loadBalancer:        
        servers:          
          - url: http://libre:9980
             
    sfu:
      loadBalancer:        
        servers:         
          - url: http://sfu:7000
           
                   